language: generic
matrix:
  include:
    - os: linux
      sudo: false
    - os: osx
install:
  # Install acceptance test dependencies for OSX
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then which gsed || brew install gnu-sed; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then which gtimeout || brew install coreutils; fi
  # Show versions used
  - bash --version
script: test/acceptance.sh
